### ISSUE TITLE
[build error]

### ISSUE THREAD

**Issue by phamhuong8794** [amplitude/unity-plugin#42]
I am trying build a new project with amplitude same tutorial. but app is crash immediately when i open app. this is error:
![Capture](https://user-images.githubusercontent.com/9448079/85372335-e2cda200-b55b-11ea-835b-e2126977f6f1.PNG)
![Capture2](https://user-images.githubusercontent.com/9448079/85372341-e4976580-b55b-11ea-84c5-05e3a10df732.PNG)
![Capture3](https://user-images.githubusercontent.com/9448079/85372346-e5c89280-b55b-11ea-9236-39e4d19b4f09.PNG)

**Comment by haoliu-amp** [comment]
Hello, it's not a bug. Please make sure you follow the step 2 from our doc.
https://developers.amplitude.com/docs/unity

**Comment by phamhuong8794** [comment]
thanks for answer. i'd build success but have a error when i'm trying log an event. this is error in picture
![Capture](https://user-images.githubusercontent.com/9448079/85490850-b61d9700-b5fc-11ea-85f8-37f31693a202.PNG)

**Comment by phamhuong8794** [comment]
if you have video setup, please send me

**Comment by phamhuong8794** [comment]
![image](https://user-images.githubusercontent.com/9448079/85516223-2e4d8200-b628-11ea-8f8b-19d22be93e04.png)
![image](https://user-images.githubusercontent.com/9448079/85516266-3a394400-b628-11ea-8af8-320a70cd7094.png)
![image](https://user-images.githubusercontent.com/9448079/85516321-46bd9c80-b628-11ea-963c-5021e86106ef.png)
![image](https://user-images.githubusercontent.com/9448079/85516401-5b019980-b628-11ea-90d9-446e0acdba3b.png)
![image](https://user-images.githubusercontent.com/9448079/85516440-648b0180-b628-11ea-9f00-35dfa904cfd0.png)

**Comment by haoliu-amp** [comment]
@phamhuong8794 Can you try add 
```
-keep class com.amplitude.unity.plugins.AmplitudePlugin { *; }
```
to your Proguard exceptions file?

**Comment by phamhuong8794** [comment]
2020-06-25 09:41:37.651 27740-27740/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-06-25 09:41:37.652 27740-27740/? E/libpersona: scanKnoxPersonas
2020-06-25 09:41:37.652 27740-27740/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
2020-06-25 09:41:38.246 27740-27740/com.android.application E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.application, PID: 27740
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/unity3d/player/UnityPlayer;
        at com.unity3d.player.UnityPlayerActivity.onCreate(Unknown Source:7)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unity3d.player.UnityPlayer" on path: DexPathList[[zip file "/data/app/com.android.application-QqsCvCzcpl4HUeWyktLyiw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.application-QqsCvCzcpl4HUeWyktLyiw==/lib/arm, /data/app/com.android.application-QqsCvCzcpl4HUeWyktLyiw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.unity3d.player.UnityPlayerActivity.onCreate(Unknown Source:7) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
<error if i change this proguard>

**Comment by haoliu-amp** [comment]
This error seems strange. I'm not sure why your proguard is behaving this way.

The idea is not to obfuscate `com.amplitude.unity.plugins.AmplitudePlugin` class and its methods. 

Which is this - 
```
-keep class com.amplitude.unity.plugins.AmplitudePlugin
```

I don't think that's the issue in our tutorial. Maybe you can create a clean project to test it out.

**Comment by phamhuong8794** [comment]
i'm create 4 times new project, and result is same. have issue of unity version??? i'm working in unity 2017.4.31f1. I'm don't find every package name is com.amplitude.unity.plugins.AmplitudePlugin in package

**Comment by phamhuong8794** [comment]
Do I need to import that sdk into the project?

**Comment by phamhuong8794** [comment]
i trying up to unity 2018.4.23f1, it same (@@)

**Comment by phamhuong8794** [comment]
If possible, please give me a video of how to add the library

**Comment by phamhuong8794** [comment]
Thanks haoliu,
I have finished adding amplitude to my project. There are some issues that hopefully help someone in need:
1. i'm update version unity to 2018
2. user lastest resolve jar
3. replace -keep class com.amplitude.unity.plugins.AmplitudePlugin { *; } instead -keep class com.amplitude.unity.plugins.AmplitudePlugin
4. This is how to add proguard file into unity: https://stackoverflow.com/questions/43774062/crashlytics-unity-plugin-export-to-android-studio/46840109#46840109
Goodluck!!

**Comment by haoliu-amp** [comment]
@phamhuong8794 Glad you figured it out! Thanks for sharing the steps too!
